version: '4'

name: custom-ackermann-steering-controller-ros

services:
  ros-noetic-master:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /workspace        
    volumes:
      - ../:/workspace/src/custom_ackermann_steering_controller_ros
    env_file:
      - ./.env
    tty: true

